### ISSUE TITLE
autoscan triggers two libraries to scan

### ISSUE THREAD

**Issue by moooep** [Cloudbox/autoscan#101]
i just set up autoscan using "bernard". 

im having just one issue. in some cases autoscan triggers multiple libraries to scan. in this case plex won't find any new file.

of course the path is not set to both of these libraries. 

for example: 

```
Mar 11 10:07:32 INF Scan moved to target library="Serien (GER)" path="/mnt/fclone/fusion/tvshows-4k/Snowpiercer (2020) [tvdbid-364928]/Season 02" target=plex url=http://plex-0:32400

Mar 11 10:07:32 INF Scan moved to target library="Serien 4K (GER)" path="/mnt/fclone/fusion/tvshows-4k/Snowpiercer (2020) [tvdbid-364928]/Season 02" target=plex url=http://plex-0:32400
```

or 

```
Mar 11 13:04:14 INF Scan moved to target library="Serien (GER)" path="/mnt/fclone/fusion/tvshows-trash/The Bachelor (DE) (2003) [tvdbid-265925]/Season 11" target=plex url=http://plex-0:32400

Mar 11 13:04:14 INF Scan moved to target library="Serien Reality-TV (GER)" path="/mnt/fclone/fusion/tvshows-trash/The Bachelor (DE) (2003) [tvdbid-265925]/Season 11" target=plex url=http://plex-0:32400
```

**Comment by m-rots** [comment]
In this particular case, what was the path received by the trigger?

**Comment by moooep** [comment]
wow thats a fast response .. 

Library "Serien (GER)" is set to the path 
`/mnt/fclone/fusion/tvshows`

Serien 4K (GER):
`/mnt/fclone/fusion/tvshows-4k`

Serien Reality-TV: 
`/mnt/fclone/fusion/tvshows-trash`

**Comment by m-rots** [comment]
Okay cool, this matches my hypothesis. Will get onto it ASAP. Thanks for the report!

**Comment by moooep** [comment]
well, thank you for helping!

**Comment by m-rots** [comment]
If you're using Autoscan with Docker, then you can switch the image over to `cloudb0x/autoscan:trailing-slash` to check whether that solves your issue. If it does, do let me know!

**Comment by moooep** [comment]
looks preety perfekt now! i will keep an eye on that :) thanks a lot!
