### ISSUE TITLE
Issue with radarr (SQL column missing)

### ISSUE THREAD

**Issue by OriginalZarby** [Cloudbox/autoscan#113]
Hey I tried to use autoscan with radarr and have an issue.

![1](https://user-images.githubusercontent.com/41742148/115157619-8dcebf80-a08a-11eb-85ae-0596deaf2d37.png)

As you can see from the screenshot the test succeeds.
But saving it fails

![2](https://user-images.githubusercontent.com/41742148/115157675-d1292e00-a08a-11eb-9e9e-58562dd27c11.png)

And I get theese errors in the logs (I obviously added the trigger in my config file)

![5](https://user-images.githubusercontent.com/41742148/115158128-fd45ae80-a08c-11eb-97f4-40a4eef1cfdd.png)

![3](https://user-images.githubusercontent.com/41742148/115157707-03d32680-a08b-11eb-9b2e-fcc3a3274203.png)
![4](https://user-images.githubusercontent.com/41742148/115157710-05045380-a08b-11eb-8f7a-0bcb1ac116b9.png)

As you can see in the logs I get a missing SQL column for OnDelete (the On delete option is not checked in radarr).
Is it normal ?
Is it a configuration issue ?

**Comment by m-rots** [comment]
From a first glance, this issue appears to be specific to Radarr.

**Comment by OriginalZarby** [comment]
Is there a way to fix it ?

**Comment by m-rots** [comment]
I have no idea, I'd recommend to open an issue on [Radarr's GitHub](https://github.com/Radarr/Radarr).

**Comment by TheNexter** [comment]
I confirm the problem, but they can be solve with radarr install in nightly version
