### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by s01ice** [Cloudbox/autoscan#124]
Hi I'm getting this error below. Can anyone help me with this?

> Jul  4 00:38:16 INF Initialised processor anchors=["/mnt/unionfs/.anchors/media.anchor"] min_age=2m30s,
panic: runtime error: invalid memory address or nil pointer dereference,
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x9ae32c],
,
goroutine 1 [running]:,
github.com/m-rots/stubbs.ParseKey(0x0, 0x0, 0xc000214080, 0x0, 0x0),
	github.com/m-rots/stubbs@v1.1.0/stubbs.go:73 +0x6c,
github.com/m-rots/stubbs.FromFile(0xc0000ab290, 0xf, 0xc0002181a0, 0x1, 0x1, 0x0, 0x0, 0x0, 0xc00009f3c0, 0x1, ...),
	github.com/m-rots/stubbs@v1.1.0/stubbs.go:105 +0x10a,
github.com/cloudbox/autoscan/triggers/bernard.New(0xc0000ab290, 0xf, 0xc0000ab2a4, 0xb, 0x0, 0x0, 0x0, 0x0, 0xc00014df40, 0x1, ...),
	github.com/cloudbox/autoscan/triggers/bernard/bernard.go:48 +0x445,
main.main(),
	github.com/cloudbox/autoscan/cmd/autoscan/main.go:220 +0xfc8

**Comment by m-rots** [comment]
Looks to me like your service account JSON key file is invalid

**Comment by s01ice** [comment]
Thank you, created a new service account and dl the json again.

Now I have a different problem, communication I believe: I'm running Autoscan and Plex in docker and I've tried multiple url for plex in  config.yml

See errors below:dial tcp in many attempts do not match my server address

**1: http://localhost:32400**
Jul  6 01:16:56 FTL Failed initialising target error="version: Get \"http://localhost:32400/\": dial tcp 127.0.0.1:32400: connect: connection refused: target unavailable" target=plex target_url=http://localhost:32400

**2: http://plex:32400**
Jul  6 01:15:34 FTL Failed initialising target error="version: Get \"/\": unsupported protocol scheme \"\": target unavailable" target=plex target_url=

**3: http://172.18.0.2**
Jul  6 01:13:39 FTL Failed initialising target error="version: Get \"http://172.18.0.2/\": dial tcp 172.18.0.2:80: connect: connection refused: target unavailable" target=plex target_url=http://172.18.0.2

**4: http://172.18.0.2:32400**
Jul  6 01:15:34 FTL Failed initialising target error="version: Get \"/\": unsupported protocol scheme \"\": target unavailable" target=plex target_url=

**Docker networks:**
Network | IP Address | Gateway
bridge | 172.17.0.2 | 172.17.0.1
plexguide | 172.18.0.2 | 172.18.0.1

Network | IP Address | Gateway
bridge | 172.17.0.2 | 172.17.0.1
plexguide | 172.18.0.2 | 172.18.0.1

**Comment by l3uddz** [comment]
As mentioned by @m-rots, key is invalid.
