### ISSUE TITLE
trigger: Readarr

### ISSUE THREAD

**Issue by ExtraChoccyMilk** [Cloudbox/autoscan#128]
Would it be possible to add Readarr as one of the triggers in the config.yml? I currently put the path to point to my audiobooks folder location and autoscan usually grabs those files, but it sometimes misses them and I have to manually refresh my audiobooks library in Plex.

**Comment by voltron4lyfe** [comment]
I'm working on this.

**Comment by voltron4lyfe** [comment]
https://github.com/Cloudbox/autoscan/pull/143 contains a pull-request for this.
