### ISSUE TITLE
Don't remove trailing / on manual scan requests

### ISSUE THREAD

**Issue by edrock200** [Cloudbox/autoscan#145]
Hello
Have a unique request, occasionally I would like to use the /triggers/manual web page to refresh an entire root folder across multiple apps. When I do this, it doesn't work because it says root library cannot be determined. I *think* this is because autoscan appears to automatically remove the trailing / on submitted requests. Respectfully requesting that this auto removal be removed so that root folders can be submitted for scan requests. I tested this by putting on /path/to/root/folder/* and auto scan no longer threw the error, however, it submits it as litteral, so it obviously didn't scan the root folder.

Thanks in advance for your consideration. 
Ed

**Comment by g4m3r7ag** [comment]
Same issue, I even tried submitting the curl with a double slash (%2F%2F) at the end and it removed both.

**Comment by m-rots** [comment]
We currently have this trailing slash removal implemented to avoid accidental scans of entire libraries (which can take considerable amounts of time). Autoscan is designed to optimise scans around film/show/season specific directories and such a full library scan would do away with these optimisations. I recommend to either manually trigger a full library scan inside the Plex UI or, similarly to how Autoscan is implemented, manually call the `/refresh` Plex API endpoint.
