### ISSUE TITLE
Same issue as #99 - inotify no space left on device

### ISSUE THREAD

**Issue by Fma965** [Cloudbox/autoscan#152]
I'm having the same issue as #99  but with a local mount and i have set the max watches as a extreme test to 524288 

Mar 16 21:11:42 ERR Failed initialising jobs error="watch directory: /mnt/local/Media: no space left on device" trigger=inotify

FWIW i'm running the docker container, not sure if that matters?

**Comment by edrock200** [comment]
How many objects do you have in that dir? FWIW, I have set inotify as high as 10 million without issue. So as a test, you can try bumping it up really high to see if the error clears, then lowering in increments. The one thing I'm not sure of is if the container needs restarted after updating inotify setting on the host, I think it does but I'm not 100% on that.

**Comment by Fma965** [comment]
Not many objects at all, we would be talking like maybe 100 files, if that. i also tried with higher than 524288 but it made no difference, ofcourse restarting the container after the tests. 

Everything other than inotify works fine :)

**Comment by Fma965** [comment]
So it seems i had multiple fs.inotify.max_user_watches lines in my sysctl, fixed :)

**Comment by lightmaster** [comment]
how do you change sysctl such that it's not lost when recreating the container?
