### ISSUE TITLE
Receiving 404 error from all ARR's

### ISSUE THREAD

**Issue by Kazz3r24** [Cloudbox/autoscan#161]
Port 3030 is open and the scripts is running per netstat. Autoscan is running on the host Plex is running on. ARR's are on a separate host connected via SFP point to point link.

`sudo netstat -tulpn | grep :3030`
`tcp        0      0 10.10.10.9:3030         0.0.0.0:*               LISTEN      28747/autoscan`

`Invalid request Validation failed: `
` -- Url: Unable to post to webhook: HTTP request failed: [404:NotFound] [PUT] at [http://10.10.10.9:3030/triggers/:sonarr]`

config.yml

`  sonarr:
    - name: sonarr # /triggers/sonarr
      priority: 2

     
      rewrite:
        - from: /mnt/Echo/TV\ Shows/
          to: /mnt/Foxtrot/TV\ Shows/`

**Comment by Kazz3r24** [comment]
After several hours I gave up on getting this to work with my ARR's, instead I've got autoscan to autoscan configured which is working fine.

Plex: autoscan (inotify config)
ARRS: autoscan (inotify + autoscan config)
Works awesome.

**Comment by Kazz3r24** [comment]
Same issue still around, manual works fine but the ARR triggers don't work at all.

**Comment by Kazz3r24** [comment]
Fixed it myself through trial and error. Not sure what the Readme content is based off but it's either old or just wrong.

For anyone else who may happen upon this, the correct syntax for your config is as follows: (don't just copy/paste from the web). Using notepad++ set to YAML language was a lifesaver.

` radarr:
   - name: radarr   # /triggers/radarr
     priority: 2

     # Rewrite the path from within the container
     # to your local filesystem.
     rewrite:
        - from: /mnt/Echo/Movies/
          to: /mnt/Foxtrot/Movies/


   - name: radarr4k # /triggers/radarr4k
     priority: 5

     # Rewrite the path from within the container
     # to your local filesystem.
     rewrite:
        - from: /mnt/Echo/Movies 4K/
          to: /mnt/Foxtrot/Movies 4K/


 sonarr:
   - name: sonarr   # /triggers/sonarr
     priority: 2

     # Rewrite the path from within the container
     # to your local filesystem.
     rewrite:
        - from: /mnt/Echo/TV Shows/
          to: /mnt/Foxtrot/TV Shows/
`

Then in your ARR the webhook URL should look like this:

`http://10.10.10.10:3030/triggers/radarr`

For some reason the guide suggests adding "triggers/:radarr" which is incorrect - this gives the 404 I was getting.

**Comment by lightmaster** [comment]
Thank you for this. Spent twenty minutes checking over all my settings to make sure they matched the readme, never thought about that the readme could be wrong.

**Comment by JSouthGB** [comment]
> Then in your ARR the webhook URL should look like this:
> 
> `http://10.10.10.10:3030/triggers/radarr`
> 
> For some reason the guide suggests adding "triggers/:radarr" which is incorrect - this gives the 404 I was getting.

Thank you for sharing. This was my exact problem.

**Comment by Kazz3r24** [comment]
Glad you got it working! I have no idea how this issue wasn't more wide-spread...because the documentation is literally wrong. I just assume at this point the project has been abandoned which is unfortunate (at least it still works).

If it isn't abandoned then the author needs to put in some time to fix the documentation.

**Comment by JSouthGB** [comment]
> I have no idea how this issue wasn't more wide-spread...because the documentation is literally wrong. 

I figure most folks are smarter than me and understand it's a typo. Best guess I have. (apologies if that includes you by extension, lol)

> I just assume at this point the project has been abandoned which is unfortunate (at least it still works).
> 
> If it isn't abandoned then the author needs to put in some time to fix the documentation.

This project is a rewrite of the original plex_autoscan, so it may be rounded out pretty well by now. I'd submit a pr to correct the docs if I knew how. Is a pr in your wheelhouse perhaps?

**Comment by Kazz3r24** [comment]
> I figure most folks are smarter than me and understand it's a typo.

Typo's are okay in text messages and email etc, but in "official" documentation for how to install or operate something - you just can't have that. I work in IT, I'm picky. Proof read what you post, it's not hard. Hell, any time I go to publish documentation of any kind, I run through it as written in the post before I publish it. If it doesn't work for me following what I've written, it won't work for anyone else lol. It also would have completely mitigated this issue being created in the first place ;).

Not to jump down your throat about it lol.



> This project is a rewrite of the original plex_autoscan, so it may be rounded out pretty well by now. I'd submit a pr to correct the docs if I knew how. Is a pr in your wheelhouse perhaps?

I know and it is pretty well rounded out I agree. There are definitely some bugs/issues with it though that could use some love and this hasn't seen an update in a while. I don't really see the point in putting effort into a PR, there's still 2 PR's waiting to be pulled, so even if I did, it'll likely never get pulled. I'd be better off just forking this repo and fixing it there. I just wouldn't be able to support it whatsoever lol.
