### ISSUE TITLE
no space left on device

### ISSUE THREAD

**Issue by warlordattack** [Cloudbox/autoscan#180]
I have 5tb free space on my nas and have some errors saying no free space left : 

11/28/2022 9:41:49 PM
Nov 28 21:41:48 INF Processor started
11/28/2022 9:41:49 PM
Nov 28 21:41:49 ERR Failed initialising jobs error="watch directory: /partage/musique/_diff: no space left on device" trigger=inotify

11/28/2022 9:12:31 PM
Nov 28 21:12:30 INF Starting server on port 3030
11/28/2022 9:12:31 PM
Nov 28 21:12:30 ERR Failed initialising jobs error="watch directory: /partage/media/music/‐M‐/Rêvalité Augmentée (2022)/Digital Media 02: no space left on device" trigger=inotify

In this folder : /partage/musique/_diff
i have only one sub folder with 15 files inside

**Comment by jobrien2001** [comment]
same

Dec  1 02:54:19 ERR Failed initialising jobs error="watch directory: /media: no space left on device" trigger=inotify

**Comment by m-rots** [comment]
Please checkout both #99 and #152. The error message isn't super helpful but it actually has to do with inotify watch limits, which in both your cases occurs when Autoscan has to watch many subdirectories (it has to watch each individual Film/TV folder).

**Comment by jobrien2001** [comment]
Thank you, I increased the limit and its working fine now.

/etc/sysctl.conf 
increase fs.inotify.max_user_watches

then 
sysctl -p
