### ISSUE TITLE
Config.yml not being created

### ISSUE THREAD

**Issue by NightMean** [Cloudbox/autoscan#189]
I'm just setting up autoscan for the first time but whenever I try to run the v.1.3.0 linux amd64 binary I receive an error message saying
`FTL Failed opening config error="open /root/.config/autoscan/config.yml: no such file or directory"`

The readme doesn't mention anything regarding creating the file manually so I'm bit confused if this is a bug or just a missing setup instruction.
The activity.log is being created so this shouldn't be a permission issue.

**Comment by Dataninja126** [comment]
> 

I'm experiencing the same, did you ever find a solution?

**Comment by m-rots** [comment]
This is intentional as the targets have to be known up-front. However, the readme is full of examples on how to setup the config file manually! :)

We currently have no plans for guided config creation (e.g. similar to RClone). Closing in favour of #46.

**Comment by Dataninja126** [comment]
> This is intentional as the targets have to be known up-front. However, the readme is full of examples on how to setup the config file manually! :)
> 
> We currently have no plans for guided config creation (e.g. similar to RClone). Closing in favour of #46.

Thanks, I was able to partially solve the error by creating the config.yml with some basic configurations.
