### ISSUE TITLE
inotify workaround for CIFS?

### ISSUE THREAD

**Issue by edrock200** [Cloudbox/autoscan#51]
My understanding is inotify won't work with CIFS shares. Is there a way to do a ls -R type function on a cron schedule to parse out deltas for autoscan? Thanks in advance!

**Comment by m-rots** [comment]
The Inotify trigger is build on the [fsnotify](https://github.com/fsnotify/fsnotify) Go module which sadly does not have polling support. It is listed as a *maybe* but unfortunately it has been for quite some time.

We will **not** be rolling our own solution as that would be out-of-scope of the general project and requires a serious investment in time.
