### ISSUE TITLE
Precompiled binaries for ARM

### ISSUE THREAD

**Issue by agneevX** [Cloudbox/autoscan#55]
Would be nice if we could get binaries for the Raspberry Pi, which is based on ARM in both 32-bit and 64-bit.

**Comment by m-rots** [comment]
Agreed! I’m not really happy with the build system in its current state... But if we’re going to revamp it, then I’ll definitely include more architectures!

**Comment by l3uddz** [comment]
when/if the `refactor-bernard` branch is merged into master the following binaries will be built:

**Linux & Docker Arch**

- amd64
- arm64
- armv7

**Darwin**

- amd64
- arm64 (**this will follow once supported by the new sqlite driver**)
