### ISSUE TITLE
More questions than issues...

### ISSUE THREAD

**Issue by edrock200** [Cloudbox/autoscan#56]
Thanks again for making another awesome media server utility.

I had a few questions about the bernard google drive monitorig.

I see it now relies on json files. Does this mean it will not work with "My Drive" since service accounts, as far as I know, can't be granted rights on my drive?

Second, does Drive ID with Bernard mean the actual drive name or the drive ID string, e.g. the team drive ID from rclone?

**Comment by m-rots** [comment]
Autoscan indeed does not work with "My Drive". Instead, it exclusively works with Shared Drives and Service Accounts.

With Drive ID we mean the drive ID string indeed.
