### ISSUE TITLE
Team Drive Sync Error

### ISSUE THREAD

**Issue by edrock200** [Cloudbox/autoscan#58]
I started getting this error to a TD. I deleted the autoscan.db and let it rebuild, but it still happens after a full rebuild:
`ERR Consecutive errors occurred while syncing drive, drive has been stopped... error=["REMOVED: performing partial sync: ID does not exist from hook: datastore: data anomaly","REMOVED: performing partial sync: ID does not exist from hook: datastore: data anomaly","REMOVED: performing partial sync: ID does not exist from hook:`

Any ideas on what could be causing this?

**Comment by m-rots** [comment]
Sadly this seems to occur every now and then. Google Drive is not always correct when synchronising so your best bet is to wait for Drive to fix itself (minutes to hours). A database rebuild should only be necessary when this issue goes on for a full 24 hours.

Unfortunately Bernard and Google Drive are not perfect and thus it remains to be seen whether this issue will be fixed long term.

**Comment by l3uddz** [comment]
please try the `refactor-bernard` branch, this will hopefully no longer be an issue.

**note: you will need to remove your existing database (`.db`) file.**

**Comment by edrock200** [comment]
Will do, thanks!!

**Comment by l3uddz** [comment]
had a chance to test this new build / version and can confirm whether you are still seeing this issue ?

**Comment by edrock200** [comment]
I'm embarassed to admit I'm having a heck of a time compiling the binaries for that branch. Do any pre-compiled binaries exist for Linux AMD64 (Ubuntu)? Apologies and thanks in advance. I tried following the Go compile instructions but it's throwing several errors for me, it appears it needs these various packages and they don't exist:
`cmd/autoscan/main.go:13:2: cannot find package "github.com/alecthomas/kong" in any of:
        /usr/lib/go-1.10/src/github.com/alecthomas/kong (from $GOROOT)
        /root/go/src/github.com/alecthomas/kong (from $GOPATH)
cmd/autoscan/main.go:19:2: cannot find package "github.com/cloudbox/autoscan" in any of:
        /usr/lib/go-1.10/src/github.com/cloudbox/autoscan (from $GOROOT)
        /root/go/src/github.com/cloudbox/autoscan (from $GOPATH)
cmd/autoscan/main.go:20:2: cannot find package "github.com/cloudbox/autoscan/migrate" in any of:
        /usr/lib/go-1.10/src/github.com/cloudbox/autoscan/migrate (from $GOROOT)
        /root/go/src/github.com/cloudbox/autoscan/migrate (from $GOPATH)
cmd/autoscan/main.go:21:2: cannot find package "github.com/cloudbox/autoscan/processor" in any of:
        /usr/lib/go-1.10/src/github.com/cloudbox/autoscan/processor (from $GOROOT)
        /root/go/src/github.com/cloudbox/autoscan/processor (from $GOPATH)
cmd/autoscan/main.go:22:2: cannot find package "github.com/cloudbox/autoscan/targets/autoscan" in any of:
        /usr/lib/go-1.10/src/github.com/cloudbox/autoscan/targets/autoscan (from $GOROOT)
        /root/go/src/github.com/cloudbox/autoscan/targets/autoscan (from $GOPATH)
cmd/autoscan/main.go:23:2: cannot find package "github.com/cloudbox/autoscan/targets/emby" in any of:
        /usr/lib/go-1.10/src/github.com/cloudbox/autoscan/targets/emby (from $GOROOT)
        /root/go/src/github.com/cloudbox/autoscan/targets/emby (from $GOPATH)
cmd/autoscan/main.go:24:2: cannot find package "github.com/cloudbox/autoscan/targets/jellyfin" in any of:
        /usr/lib/go-1.10/src/github.com/cloudbox/autoscan/targets/jellyfin (from $GOROOT)
        /root/go/src/github.com/cloudbox/autoscan/targets/jellyfin (from $GOPATH)
cmd/autoscan/main.go:25:2: cannot find package "github.com/cloudbox/autoscan/targets/plex" in any of:
        /usr/lib/go-1.10/src/github.com/cloudbox/autoscan/targets/plex (from $GOROOT)
        /root/go/src/github.com/cloudbox/autoscan/targets/plex (from $GOPATH)
cmd/autoscan/main.go:26:2: cannot find package "github.com/cloudbox/autoscan/triggers" in any of:
        /usr/lib/go-1.10/src/github.com/cloudbox/autoscan/triggers (from $GOROOT)
        /root/go/src/github.com/cloudbox/autoscan/triggers (from $GOPATH)
cmd/autoscan/main.go:27:2: cannot find package "github.com/cloudbox/autoscan/triggers/bernard" in any of:
        /usr/lib/go-1.10/src/github.com/cloudbox/autoscan/triggers/bernard (from $GOROOT)
        /root/go/src/github.com/cloudbox/autoscan/triggers/bernard (from $GOPATH)
cmd/autoscan/main.go:28:2: cannot find package "github.com/cloudbox/autoscan/triggers/inotify" in any of:
        /usr/lib/go-1.10/src/github.com/cloudbox/autoscan/triggers/inotify (from $GOROOT)
        /root/go/src/github.com/cloudbox/autoscan/triggers/inotify (from $GOPATH)
cmd/autoscan/main.go:29:2: cannot find package "github.com/cloudbox/autoscan/triggers/lidarr" in any of:
        /usr/lib/go-1.10/src/github.com/cloudbox/autoscan/triggers/lidarr (from $GOROOT)
        /root/go/src/github.com/cloudbox/autoscan/triggers/lidarr (from $GOPATH)
cmd/autoscan/main.go:30:2: cannot find package "github.com/cloudbox/autoscan/triggers/manual" in any of:
        /usr/lib/go-1.10/src/github.com/cloudbox/autoscan/triggers/manual (from $GOROOT)
        /root/go/src/github.com/cloudbox/autoscan/triggers/manual (from $GOPATH)
cmd/autoscan/main.go:31:2: cannot find package "github.com/cloudbox/autoscan/triggers/radarr" in any of:
        /usr/lib/go-1.10/src/github.com/cloudbox/autoscan/triggers/radarr (from $GOROOT)
        /root/go/src/github.com/cloudbox/autoscan/triggers/radarr (from $GOPATH)
cmd/autoscan/main.go:32:2: cannot find package "github.com/cloudbox/autoscan/triggers/sonarr" in any of:
        /usr/lib/go-1.10/src/github.com/cloudbox/autoscan/triggers/sonarr (from $GOROOT)
        /root/go/src/github.com/cloudbox/autoscan/triggers/sonarr (from $GOPATH)
cmd/autoscan/config.go:4:2: cannot find package "github.com/kirsle/configdir" in any of:
        /usr/lib/go-1.10/src/github.com/kirsle/configdir (from $GOROOT)
        /root/go/src/github.com/kirsle/configdir (from $GOPATH)
cmd/autoscan/main.go:14:2: cannot find package "github.com/natefinch/lumberjack" in any of:
        /usr/lib/go-1.10/src/github.com/natefinch/lumberjack (from $GOROOT)
        /root/go/src/github.com/natefinch/lumberjack (from $GOPATH)
cmd/autoscan/main.go:15:2: cannot find package "github.com/rs/zerolog" in any of:
        /usr/lib/go-1.10/src/github.com/rs/zerolog (from $GOROOT)
        /root/go/src/github.com/rs/zerolog (from $GOPATH)
cmd/autoscan/main.go:16:2: cannot find package "github.com/rs/zerolog/log" in any of:
        /usr/lib/go-1.10/src/github.com/rs/zerolog/log (from $GOROOT)
        /root/go/src/github.com/rs/zerolog/log (from $GOPATH)
cmd/autoscan/config.go:5:2: cannot find package "golang.org/x/sys/unix" in any of:
        /usr/lib/go-1.10/src/golang.org/x/sys/unix (from $GOROOT)
        /root/go/src/golang.org/x/sys/unix (from $GOPATH)
cmd/autoscan/main.go:17:2: cannot find package "gopkg.in/yaml.v2" in any of:
        /usr/lib/go-1.10/src/gopkg.in/yaml.v2 (from $GOROOT)
        /root/go/src/gopkg.in/yaml.v2 (from $GOPATH)
cmd/autoscan/main.go:35:2: cannot find package "modernc.org/sqlite" in any of:
        /usr/lib/go-1.10/src/modernc.org/sqlite (from $GOROOT)
        /root/go/src/modernc.org/sqlite (from $GOPATH)`

**Comment by m-rots** [comment]
@edrock200 it looks like you're using Golang 1.10. Autoscan requires Go 1.16 or later for this branch.

**Comment by edrock200** [comment]
ahh my bad. let me try that

**Comment by edrock200** [comment]
Thanks for pointing this out. Even though I installed 1.16 it was reverting to 1.10 in another location. I forced it to use 1.16 and it compiled.  :) I deleted my autoscan.db's on both autoscan instances, copied the file over, and I just started both services (both just today gave me the bernard anomaly failures and were stuck at that status, so hopefully this is a good test case.) I'll report back. Thanks again!!

**Comment by m-rots** [comment]
Changes are now in the master branch! If someone reports new issues, please comment on this issue so we can re-open it.

**Comment by l3uddz** [comment]
P.S.

You can grab compiled binaries from the CI build status page: 

https://github.com/Cloudbox/autoscan/actions/runs/665961903

**Comment by m-rots** [comment]
@edrock200 binaries are now also available at https://github.com/Cloudbox/autoscan/actions/runs/665961903

**Comment by edrock200** [comment]
Thank you! And the latest version is working for me, full index completed successfully and triggers sending! You rock!
