### ISSUE TITLE
ARM supported docker image

### ISSUE THREAD

**Issue by kdckrs** [Cloudbox/autoscan#63]
Can we get an ARM (32-bit + 64-bit) supported docker image so we can work with it on Raspberry Pi's?

**Comment by m-rots** [comment]
Hotio offers ARM builds at the moment: https://hub.docker.com/r/hotio/autoscan/tags.

I don't think we will move to a new build system any time soon so I cannot say that Autoscan's Docker images will offer this too in the near future.

**Comment by m-rots** [comment]
I'll close this for now in favour of #55.
