### ISSUE TITLE
service-account.json

### ISSUE THREAD

**Issue by xfouloux** [Cloudbox/autoscan#87]
Hi,

thanks for the tool ! coming from the old plex_autoscan,

what should be the format and keys of the file service-account.json ?

Thanks

**Comment by timmehtimtims** [comment]
The following has worked for me:
1. go to your api project in google developer console and create a new service account
2. once you create the key download it is as a .json
3. rename it 'service-account.json'
4. upload the file to your server wherever your autoscan directory is located eg: /my/appdata/autoscan/service-account.json
5. add the file to your config.yml pointing to the path in the container: /config/service-account.json 
6. add the service account email address to the shared drive(s) that you want it to manage and give it the correct permissions
7. DONE!

**Comment by xfouloux** [comment]
Oh thanks ! I'll do this asap =) !
