### ISSUE TITLE
Errors in logs and not working

### ISSUE THREAD

**Issue by Daskew78** [Cloudbox/autoscan#92]
I'm getting errors in my logs and it's not working... Sorry I can't be more descriptive but i'm not technical. I'm trying to get it working with Plex and to the best of my knowledge everything else is setup correctly and I'm told these errors are a docker problem. Please see the attached file.
[_autoscan_logs.txt](https://github.com/Cloudbox/autoscan/files/5997087/_autoscan_logs.txt)

**Comment by l3uddz** [comment]
if you are using the cloudb0x docker image, please try the `inotify-err-check` tag as it should no longer panic and throw an error. 

it may be permission related.

**Comment by Daskew78** [comment]
Thank you, that appears to have worked. However, it was working on the first time I set it up then later stopped so unless you're confident this is a fix I would like to keep monitoring the issue an report back in a day or so to confirm everything is still okay?

**Comment by l3uddz** [comment]
yep, thats fine with me. 

thanks for your report!

**Comment by Daskew78** [comment]
thanks for your help :)

**Comment by Daskew78** [comment]
Not sure if this is related but i'm seeing these errors in the logs?
Feb 17 18:36:08 FTL Failed initialising target error="version: Get \"http://plex:32400/\": dial tcp 52.58.78.16:32400: i/o timeout: target unavailable" target=plex target_url=http://plex:32400
Feb 17 18:44:04 ERR Failed initialising jobs error="walk func: /mnt/unionfs/Plex/Movies/Movies-4k: lstat /mnt/unionfs/Plex/Movies/Movies-4k: no such file or directory" trigger=inotify

**Comment by l3uddz** [comment]
This to me suggests the bug is fixed.

The bug was that it would panic (app would crash) rather than gracefully present an error.

inotify I do not believe works with fuse filesystems. 

It would be best used against the local portion of your union mount.

**Comment by Daskew78** [comment]
Okay sounds good but as said i'm not technical.... should I be worried about those errors or just ignore them?

Thanks again pal!
