### ISSUE TITLE
Error: no space left on device

### ISSUE THREAD

**Issue by timmehtimtims** [Cloudbox/autoscan#99]
Set up yesterday for the first time and it's started throwing this error:
`Mar  9 12:06:33 ERR Failed watching new directory error="watch directory: /mnt/unionfs/movies/The Perfect Teacher (2010): no space left on device" path="/mnt/unionfs/movies/The Perfect Teacher (2010)" trigger=inotify`

Have it setup to notify from radarr for the `/mnt/unionfs/movies` directory

**Comment by l3uddz** [comment]
is `/mnt/unionfs` a fuse mount? if so, inotify does not work with fuse as far as im aware.

your best option would be to point it towards a local folder, e.g. `/mnt/local/movies`

if the unionfs folder is indeed local and not a fuse mountpoint, you may be hitting an inotify watcher limit (see https://dev.to/rubiin/ubuntu-increase-inotify-watcher-file-watch-limit-kf4).

**Comment by l3uddz** [comment]
Assuming the above was the cause.
